services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - laravel
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: laravel-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog
    container_name: laravel-mailhog
    ports:
      - "8025:8025"
    networks:
      - laravel

  pusher:
    image: "docker.io/redis:alpine"  # placeholder vì Pusher không có image chính thức
    container_name: laravel-pusher
    networks:
      - laravel

  adminer:
    image: "adminer"  # Adminer for database management
    container_name: laravel-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
