services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-app
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    depends_on:
      - mysql
      - redis
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel


  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer-install
    volumes:
      - ./src:/app
    working_dir: /app
    command: ["composer", "create-project", "--prefer-dist", "laravel/laravel:^11.0", "."]

  redis:
    image: redis:alpine
    container_name: laravel-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog
    container_name: laravel-mailhog
    ports:
      - "8025:8025"
    networks:
      - laravel

  pusher:
    image: "docker.io/redis:alpine"  # placeholder vì Pusher không có image chính thức
    container_name: laravel-pusher
    networks:
      - laravel

  adminer:
    image: "adminer"  # Adminer for database management
    container_name: laravel-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - laravel

  node:
    image: node:18
    container_name: node-frontend
    working_dir: /app
    volumes:
      - ./src:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    tty: true

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
